### PR TITLE
material design lite styling for usablity and presentation

### PR DESCRIPTION
**Pull request by jenningshanna**
Using google's material design framework, updated the whole skeleton of the site.

### CODE REVIEW

**Comment by boonrs** [comment]
Evaluation page doesn't have any styling applied to it.

**Comment by boonrs** [comment]
There appears to be merge conflicts with this branch. Did you branch from the latest version of gh-pages before working on it?

**Comment by jenningshanna** [comment]
I thought I did, I can figure out the conflicts

**Comment by boonrs** [comment]
I noticed the about page has a horizontal scrollbar, other than that :+1:

**Pull request merged**
