### PR TITLE
Automate data page

### LINKED ISSUE #111: Automate Data Pages
Currently the data pages live in a folder hard-coded to a business. The data a business lives in a tab of a google spreadsheet.
- [x] Create a generic page for a business.
- [x] Remove hard-coded business names.

Out of scope:
- Customized "Overall Wellness" png. It will hard code existing diamond pngs only.

### PR DESCRIPTION
**Pull request by boonrs**
- Updated survey page url to take a parameter to specify formkeep id.
- Updated data page url to take a parameter to specify google sheet name.
- Removed redundant static pages.

Closes #111, #110, #109.

URLs for existing pages have been updated to the following:
- **All data:** /abq-financial-wellness-wizard/manage
- Mr Cog
  - **survey:** /abq-financial-wellness-wizard/?formkeep=93dd7859386d
  - **data:** /abq-financial-wellness-wizard/manage/?b=mrcog
- Cabq HR
  - **survey:** /abq-financial-wellness-wizard/?formkeep=896c3f825d22
  - **data:** /abq-financial-wellness-wizard/manage/?b=cabq-hr
- Heading Home
  - _In order for the heading home data page to work, the google sheet will need to be renamed to Heading-Home. This means you'll need to update the Zapier hook as well._
  - **survey:** /abq-financial-wellness-wizard/?formkeep=5c18f6690344
  - **data:** /abq-financial-wellness-wizard/manage/?b=headinghome

### CODE REVIEW

**Comment by ezbycer** [comment]
@jenningshanna and @williamtyner - please take a look at this ASAP and let me know if anything comes to mind.

**Comment by williamtyner** [comment]
:+1:

**Comment by jenningshanna** [comment]
@ezbycer: Been testing this and discovered a roadblock. I'll do my best to describe what is happening w/ screencaps:

When creating the Zapier hook I ran into this:
screen shot 2015-11-17 at 11 57 08 am

So I went back to formkeep but it won't allow me to go to the next step until data is collected:
screencapture-formkeep-com-f-f814a946d026-1447790256573

I tried to go to my local url and add the formkeep form ID `http://127.0.0.1:4000/abq-financial-wellness-wizard/?formkeep=f814a946d026`. And when I submitted this form it worked but the data went to the original demo bucket on formkeep:
screencapture-formkeep-com-f-b9d28c2f741a-submissions-1107783-1447790652825

**Comment by boonrs** [comment]
I was able to successfully submit a form on my local machine. Perhaps you are not on the correct branch.

@jenningshanna can you confirm you're on the correct branch with the most recent code? Perform the following steps in the terminal to verify this:
- `git fetch`
- `git checkout automate-data-page`

Then try submitting the form again.

**Comment by jenningshanna** [comment]
I also got the form to submit but now I cannot get it to generate the report for the new tab I created in the google sheet. Please take a look @boonrs 

`/abq-financial-wellness-wizard/manage/?b=testing-one`

**Comment by boonrs** [comment]
The directions were wrong for the naming convention for the sheets. It assumes the corresponding sheet is all upper case with dashes. I updated the sheet to `TESTING-ONE` and it worked.

The naming convention of the sheets can be changed to whatever you specify. I'll just need to update the code according to your rules.

**Comment by jenningshanna** [comment]
Okay @boonrs, last request: if there is no PNG present then remove this area. Otherwise good to go! :shipit:

**Comment by ezbycer** [comment]
@boonrs I think you can go ahead and merge this if the above issues have been resolved

**Pull request merged**
