### PR TITLE
The form is collecting data through FormKeep and pushing it to g-shee…

### PR DESCRIPTION
**Pull request by jenningshanna**
…ts with Zapier so we can send this evaluation as a working prototyoe early next week

### CODE REVIEW

**Comment by jenningshanna** [comment]
This is ready to merge!

**Comment by jenningshanna** [comment]
Here is where the data is collected. To test you can fill out the form and submit and it should show up in this sheet within a few minutes: https://docs.google.com/spreadsheets/d/1U_2YzAoJ55tHhtWBuYGktqun73-xDv0zxkprPqusjSs/edit#gid=0

**Comment by williamtyner** [comment]
:+1:

**Comment by boonrs** [comment]
- [ ] Text and radio buttons are not aligned in Firefox. 
- [ ] To reduce vertical scroll, consider arranging radio buttons horizontally.
  financial_wellness_calculator

**Comment by jenningshanna** [comment]
Hey ya'll, the form has only been filled out once half way according to the spreadsheet. I want to make sure they are not issues here? Also, @boonrs I am going to create a new issue for styling the buttons. I also don't want to worry about cross browser support until I've added some of our own styles.

**Pull request merged**
