### PR TITLE
Jekyll, Readme, and 2nd Pilot

### PR DESCRIPTION
**Pull request by jenningshanna**
This pull request includes:
- Jekyll Integration (all files should be here)
- updated ReadMe
- Form integration for HeadingHome Pilot

### CODE REVIEW

**Comment by boonrs** [comment]
Add __site_ to the gitignore file. Generated files shouldn't be included in repos.

**Comment by boonrs** [comment]
:+1:

**Comment by jenningshanna** [comment]
@boonrs I'm about to give up on this. Every time I try to fix the conflicts it deletes a bunch of files... like so: 
screen shot 2015-09-09 at 1 00 31 pm

I don't have a clue why this keeps happening but it's the third time now. A lot of these files are important like the layout files...

**Comment by jenningshanna** [comment]
Okay, I got everything back on my local branch but it says I am behind. Trying to figure this out!

**Comment by boonrs** [comment]
Let me know if you need help. I'll pull down a version and resolve conflicts and point you to it.

**Comment by boonrs** [comment]
Remove _site/feed.xml from the repo.

**Comment by jenningshanna** [comment]
Thanks @boonrs but I think I may have finally got it! It's took a lot of thinking and learning but I totally have a much better understanding of what's going on here and what the issue was. I also understand what a merge is much better and can easily retrace my steps in the future. Still scared to hit this merge btn though... can you give me a :+1: when you've taken a look at it?

**Comment by boonrs** [comment]
:shipit: Nice job!

**Pull request merged**
