### PR TITLE
Cursory stats

### PR DESCRIPTION
**Pull request by boonrs**
- Add a page for stats. 
- Display answer counts.

### CODE REVIEW

**Comment by boonrs** [comment]
@williamtyner: to test, pull down this branch and point your url to /manage.html

**Comment by boonrs** [comment]
This is ready for another look.

**Comment by williamtyner** [comment]
:+1:

**Comment by jenningshanna** [comment]
:shipit:

**Comment by boonrs** [comment]
closes  #5

**Pull request merged**
