### PR TITLE
Add open forum answers

### LINKED ISSUE #94: Display answers to the "Open Forum" question.
- [x] Users should see the answers one at a time.
- [x] Display in a carousel.

**Estimate:** 8 hours

### PR DESCRIPTION
**Pull request by boonrs**
Display answers one at a time in a carousel.
Closes #94.

### CODE REVIEW

**Comment by ezbycer** [comment]
@jenningshanna and @williamtyner, please take a look at this code before Becky moves forward with the merge. Let me know if any issues come up or if any changes generate questions.

**Comment by jenningshanna** [comment]
Heading Home report has a blank response or content is not showing.

**Comment by boonrs** [comment]
@jenningshanna @williamtyner I just merged in the changes from the other branch. Can you delete and recheck out this branch? I wasn't able to replicate any issues with the Heading Home report being blank.

**Comment by ezbycer** [comment]
@jenningshanna and @williamtyner, take a look at this given the update and let me know if this is good to go or if there are other requested changes.

**Comment by ezbycer** [comment]
@jenningshanna @williamtyner Let me know if merging this is still necessary... @boonrs let me know if you need any specific guidance on this pull request.

**Comment by jenningshanna** [comment]
:ship: it!

**Pull request merged**
